runtime: nodejs20

env_variables:
  NODE_ENV: 'production'
  # Credenciales de Twitter (reemplazar con valores reales en la consola de Google Cloud)
  TWITTER_API_KEY: 'kVpOupfAGVL6AIlcsI70i4OZa'
  TWITTER_API_KEY_SECRET: 'BTUN58AHIrtzOpvlGbgRXXQC7rdoxIczG73p7fl9RKGBjWpG94'
  TWITTER_ACCESS_TOKEN: 'GzUdQ8NOtkcvFxa7wflaTrloPNQovqzVlnhkJMU6'
  TWITTER_ACCESS_TOKEN_SECRET: 'X2NqzBvNCXbNRgAYSMZWCfC7rj9jw5atPRZuu10mtpEBp'
  TWITTER_CLIENT_ID: 'Mm5XSl9SQWFVR1REZ0NRMVZvZ046MTpjaQ'
  TWITTER_CLIENT_SECRET: 'l2Vgcul-_sIxLogK9MZoaQxeoZXv8GyKJgeCz-a07gCHsi3k5p'

handlers:
  # CSS - versión normal
  - url: /styles\.css
    static_files: styles.css
    upload: styles\.css
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=31536000'

  # CSS - versión minificada
  - url: /styles\.min\.css
    static_files: styles.min.css
    upload: styles\.min\.css
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=31536000'

  - url: /images/(.*\.(png|jpg|jpeg|gif|webp|svg))
    static_files: images/\1
    upload: images/.*\.(png|jpg|jpeg|gif|webp|svg)
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=31536000'

  - url: /(.*\.js)
    static_files: \1
    upload: .*\.js
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=31536000'

  # Ruta para la página principal
  - url: /
    static_files: index.html
    upload: index\.html
    secure: always

  # Ruta para la página de agradecimiento
  - url: /gracias
    static_files: gracias.html
    upload: gracias\.html
    secure: always

  # Todas las demás solicitudes se dirigen al servidor Node.js
  - url: /.*
    script: auto
    secure: always

# Configuración de escalado automático
automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  target_cpu_utilization: 0.65

# Configuración de red
network:
  session_affinity: true

# Configuración de recursos
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
